version: '3'

services:
  mongo-express:
    image: mongovip-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: vini
      ME_CONFIG_MONGODB_ADMINPASSWORD: vini22k0
    links:
      - mongo
    networks:
      - mongo-compose-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: catalog-api
      MONGO_INITDB_ROOT_USERNAME: vini
      MONGO_INITDB_ROOT_PASSWORD: vini22k0
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge