version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: catalog-api
      MONGO_INITDB_ROOT_USERNAME: vini
      MONGO_INITDB_ROOT_PASSWORD: vini22k0
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb:/data/db
