
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: catalog-api
      username: vini
      password: vini22k0

aws:
  sqs:
    catalog-queue: queueName
    catalog-queue-url: url
  bucket:
    name: bucketName